from classe import Calculadora
valor1 = int(input('Informe o 1º valor: '))
valor2 = int(input('Informe o 2º valor: '))
calc = Calculadora(valor1, valor2)
print('Soma: ')
print(calc.soma())
print('---')
print('Subtração: ')
print(calc.sub())
print('---')
print('Multiplicação: ')
print(calc.mult())
print('---')
print('Divisão: ')
print(calc.div())
print('---')

